### ISSUE TITLE
Stuhlgang hinzufügen

### ISSUE THREAD

**Issue by Niggggggo** [Andyyyyyy/stooltracker#2]
Man kann inline einen Stuhlgang hinzufügen.

**Auswahlmöglichkeiten**

1. Stuhlgangkonsistenz
Man kann die Konsistenz nach der [Bristol-Skala ](https://www.continence.org.au/pages/bristol-stool-chart.html)auswählen

2. Größe
a) klein
b) mittel
c) groß

3. Wischanzahl
0-10x Wischen

Kommt in ne Tabelle, wo pro User das oben gespeichert wird + Datum mit Uhrzeit

**Comment by Andyyyyyy** [comment]
👌
